name: Build and Test

on:
  issue_comment: null
  push: null
  pull_request: null

env:
  COMMENT_TRIGGER_PREFIX: 'Re-Trigger test workflow'

jobs:
  check-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'issue_comment' ||
              (github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith( github.event.comment.body, env.COMMENT_TRIGGER_PREFIX )) }}
    steps:
      - run: echo "Check Pass"

  build-source:
    runs-on: ubuntu-18.04
    needs: [check-comment]
    steps:
      - run: echo "Test"